-- 게스트 멤버: 계정 없이 이름만 있는 밴드 구성원. 곡 세션 배정·일정 출결에만 쓰인다.
-- 등록/수정/삭제는 관리자(OWNER)만. 실제 인물이 초대코드로 가입해도 자동 연결은 없음(관리자가 정리).
create table band_guests (
    id         bigint      generated by default as identity primary key,
    band_id    bigint      not null references bands (id) on delete cascade,
    name       varchar(50) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);
create index idx_band_guests_band on band_guests (band_id);

-- 곡 세션 슬롯에 게스트 배정. assigned_member_id 와 배타적으로 정확히 하나(또는 둘 다 null).
-- 게스트 삭제 시 배정은 자동 해제(SET NULL).
alter table song_parts
    add column assigned_guest_id bigint references band_guests (id) on delete set null;
create index idx_song_parts_assigned_guest on song_parts (assigned_guest_id);
alter table song_parts
    add constraint ck_song_part_assignee check (assigned_member_id is null or assigned_guest_id is null);

-- 일정 출결에 게스트. user_id 와 배타적으로 정확히 하나. 게스트 삭제 시 출결 행 삭제(CASCADE).
alter table attendances
    add column guest_id bigint references band_guests (id) on delete cascade;
alter table attendances
    alter column user_id drop not null;
alter table attendances
    drop constraint uq_attendance;
create unique index uq_attendance_user on attendances (schedule_id, user_id) where user_id is not null;
create unique index uq_attendance_guest on attendances (schedule_id, guest_id) where guest_id is not null;
alter table attendances
    add constraint ck_attendance_subject check ((user_id is not null) <> (guest_id is not null));
