-- 영상 좋아요. 영상당 사용자 1인 1회 (멱등). 영상·유저 삭제 시 함께 정리.
create table media_likes (
    id         bigint      generated by default as identity primary key,
    media_id   bigint      not null references media (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    constraint uq_media_like unique (media_id, user_id)
);
create index idx_media_likes_user on media_likes (user_id);
