-- 승인제 팔로우. 개인 유저가 FOLLOWERS 밴드에 팔로우 요청 → 관리자 승인 → APPROVED 팔로워는 콘텐츠 열람 가능(멤버 아님).
create table band_followers (
    id         bigint      generated by default as identity primary key,
    band_id    bigint      not null references bands (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    status     varchar(20) not null,
    decided_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_band_follower unique (band_id, user_id)
);
create index idx_band_followers_user on band_followers (user_id);
