-- 알림. 일정 등록/멤버 참가(확인용, 밴드 멤버 전체) · 팔로우 신청(FOLLOWERS 는 관리자에게 승인/거절 액션,
-- PUBLIC 즉시승인은 확인용)을 받는다. actor 는 이 알림을 유발한 사람(예: 팔로우를 신청한 사람) — 시스템성 알림은 null.
create table notifications (
    id           bigint      generated by default as identity primary key,
    recipient_id bigint      not null references users (id) on delete cascade,
    band_id      bigint      not null references bands (id) on delete cascade,
    type         varchar(30) not null,
    actor_id     bigint references users (id) on delete cascade,
    read_at      timestamptz,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
);
create index idx_notifications_recipient on notifications (recipient_id, created_at desc);
