-- Bandive 초기 스키마 (Phase 1).
-- enum 은 VARCHAR + @Enumerated(STRING). 시각은 TIMESTAMPTZ (엔티티 java.time.Instant).
-- FK 는 기본 ON DELETE CASCADE (밴드/곡/일정 삭제 시 하위 정리). 선택적 연결만 ON DELETE SET NULL.
-- 계정 삭제 기능은 없음 → user 참조 FK 도 일단 CASCADE 로 통일.

create table users (
    id         bigint generated by default as identity primary key,
    kakao_id   varchar(50)  not null unique,
    nickname   varchar(50)  not null,
    email      varchar(255),
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

create table bands (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    logo_url   varchar(500),
    banner_url varchar(500),
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

create table band_members (
    id         bigint generated by default as identity primary key,
    band_id    bigint      not null references bands (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    role       varchar(20) not null,
    joined_at  timestamptz not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_band_member unique (band_id, user_id)
);
create index idx_band_members_user on band_members (user_id);

create table invite_codes (
    id         bigint      generated by default as identity primary key,
    band_id    bigint      not null references bands (id) on delete cascade,
    code       varchar(20) not null unique,
    expires_at timestamptz,
    max_uses   integer,
    used_count integer     not null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);
create index idx_invite_codes_band on invite_codes (band_id);

create table songs (
    id                  bigint       generated by default as identity primary key,
    band_id             bigint       not null references bands (id) on delete cascade,
    title               varchar(200) not null,
    artist              varchar(200),
    status              varchar(20)  not null,
    source_type         varchar(20)  not null,
    external_track_id   varchar(100),
    memo                text,
    reference_video_url varchar(500),
    added_by            bigint       not null references users (id) on delete cascade,
    created_at          timestamptz  not null,
    updated_at          timestamptz  not null
);
create index idx_songs_band_status on songs (band_id, status);

create table song_parts (
    id                 bigint      generated by default as identity primary key,
    song_id            bigint      not null references songs (id) on delete cascade,
    instrument         varchar(20) not null,
    part_index         integer     not null,
    assigned_member_id bigint      references band_members (id) on delete set null,
    created_at         timestamptz not null,
    updated_at         timestamptz not null,
    constraint uq_song_part_slot unique (song_id, instrument, part_index)
);
create index idx_song_parts_assigned_member on song_parts (assigned_member_id);

create table votes (
    id         bigint      generated by default as identity primary key,
    song_id    bigint      not null references songs (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_vote unique (song_id, user_id)
);
create index idx_votes_user on votes (user_id);

create table schedules (
    id         bigint      generated by default as identity primary key,
    band_id    bigint      not null references bands (id) on delete cascade,
    type       varchar(20) not null,
    date_time  timestamptz not null,
    location   varchar(200),
    created_by bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null
);
create index idx_schedules_band_date_time on schedules (band_id, date_time);

create table attendances (
    id          bigint      generated by default as identity primary key,
    schedule_id bigint      not null references schedules (id) on delete cascade,
    user_id     bigint      not null references users (id) on delete cascade,
    status      varchar(20) not null,
    created_at  timestamptz not null,
    updated_at  timestamptz not null,
    constraint uq_attendance unique (schedule_id, user_id)
);
create index idx_attendances_user on attendances (user_id);

create table media (
    id          bigint       generated by default as identity primary key,
    band_id     bigint       not null references bands (id) on delete cascade,
    schedule_id bigint       references schedules (id) on delete set null,
    type        varchar(20)  not null,
    external_url varchar(500) not null,
    platform    varchar(20)  not null,
    visibility  varchar(20)  not null,
    uploaded_by bigint       not null references users (id) on delete cascade,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null
);
create index idx_media_band on media (band_id);
create index idx_media_schedule on media (schedule_id);
