-- 곡 폴더. 위시리스트/합주곡 각각 별도 (status 로 구분). 폴더 순서는 밴드장이 수동 조정.
create table song_folders (
    id         bigint generated by default as identity primary key,
    band_id    bigint       not null references bands (id) on delete cascade,
    name       varchar(60)  not null,
    status     varchar(20)  not null,   -- WISHLIST | CONFIRMED
    position   int          not null,
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

create index idx_song_folders_band_status on song_folders (band_id, status, position);

-- 곡이 속한 폴더. null = 미분류. 폴더 삭제 시 미분류로.
alter table songs
    add column folder_id bigint references song_folders (id) on delete set null;
